### ISSUE TITLE
[convention Test] Atomic design, util function 

### ISSUE THREAD

**Issue by YoonJieut** [KDT-IaaS-Class-One-Group/KDT-IaaS-image-prediction#3]
- [x] 디자인 구조론 : Atomic Desgin 컴포넌트 원자화

- https://www.notion.so/Atomic-Design-27dd8022c892494aa5dfe90a90f4bc87

- [x] util 함수 예시 공유

- fetch 함수 => 완벽하지 않으나 get fetch를 엔드포인트만 파라미터로 작성해본 함수

**Comment by YoonJieut** [comment]
@chaeyi0731 
@dev-honing 

자세한 내용은 해당 브랜치 확인바람

**Comment by YoonJieut** [comment]
![image](https://github.com/KDT-IaaS-Class-One-Group/KDT-IaaS-image-prediction/assets/122344184/ac886ba2-9859-4e3a-b790-c7c7f1866829)

![image](https://github.com/KDT-IaaS-Class-One-Group/KDT-IaaS-image-prediction/assets/122344184/a4cf3091-b0bd-47ee-9e02-d349545017a8)

**Comment by dev-honing** [comment]
감사합니다!

**Comment by chaeyi0731** [comment]
감사합니다 참고 해보도록 할게요!
